export const folders = [
	{
		name: 'AirDrops',
		icon: 'fa fa-home',
		isOpen: false,
		children: [
			{ name: 'Received', icon: 'fa fa-download' },
			{ name: 'Sent', icon: 'fa fa-upload' },
		],
	},
	{
		name: 'Documents',
		icon: 'fa fa-folder',
		isOpen: false,
		children: [
			{ name: 'Projects', icon: 'fa fa-briefcase' },
			{ name: 'Reports', icon: 'fa fa-flag' },
		],
	},
	{
		name: 'Downloads',
		icon: 'fa fa-download',
		isOpen: false,
		children: [
			{ name: 'Software', icon: 'fa fa-cogs' },
			{ name: 'Music', icon: 'fa fa-music' },
		],
	},
	{
		name: 'Photos',
		icon: 'fa fa-image',
		isOpen: false,
		children: [
			{ name: 'Vacations', icon: 'fa fa-camera' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
			{ name: 'Family', icon: 'fa fa-users' },
		],
	},
]
